# Generated by Django 2.2.6 on 2020-10-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dnaorder', '0105_auto_20201022_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioshareAccount',
            fields=[
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bioshare_account', serialize=False, to='dnaorder.Lab')),
                ('auth_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionShare',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dnaorder.Submission')),
                ('bioshare_id', models.CharField(blank=True, max_length=15, null=True)),
                ('sub_folder', models.FilePathField(allow_files=False, allow_folders=True, blank=True, null=True)),
            ],
        ),
    ]
