# Generated by Django 2.2.6 on 2020-10-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionshare',
            name='sub_folder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
