# Generated by Django 2.2.6 on 2021-08-31 17:53

from django.db import migrations, models
import django.db.models.deletion


def update_id(apps, schema_editor):
    SubmissionShare = apps.get_model('bioshare', 'SubmissionShare')
    for s in SubmissionShare.objects.all():
        s.id = '{}_{}'.format(s.submission, s.bioshare_id)
        s.save(update_fields=['id'])

class Migration(migrations.Migration):

    dependencies = [
        ('bioshare', '0002_auto_20201028_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionshare',
            name='id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='submissionshare',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dnaorder.Submission'),
        ),
        migrations.RunPython(update_id, reverse_code=migrations.RunPython.noop)
    ]
