# Generated by Django 2.2.6 on 2021-08-31 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioshare', '0003_auto_20210831_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionshare',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnaorder.Submission'),
        ),
        migrations.AlterField(
            model_name='submissionshare',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        )
        
    ]
