# Generated by Django 2.2.6 on 2021-10-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshare', '0004_auto_20210831_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionshare',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissionshare',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
