# Generated by Django 4.2.30 on 2026-05-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshare', '0005_auto_20211019_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionshare',
            name='link_to_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
